### ISSUE TITLE
PDFView shows blank on the first launch, but opening the next pdf works fine

### ISSUE THREAD

**Issue by bettdouglas** [endigo/flutter_pdfview#100]
I have this error where after first installing the app, first time opening a pdf shows a blank page yet the file exists. 

Has anyone experienced this?

**Comment by endigo** [comment]
https://github.com/endigo/flutter_pdfview/issues/98#issuecomment-676484431

**Comment by bettdouglas** [comment]
> D/com.shockwave.pdfium.PdfiumCore(13697): Starting PdfiumAndroid 1.9.0
D/jniPdfium(13697): Init FPDF library
D/jniPdfium(13697): Destroy FPDF library
E/com.shockwave.pdfium.PdfiumCore(13697): mContext may be null
W/System.err(13697): java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
W/System.err(13697): 	at com.shockwave.pdfium.PdfiumCore.renderPageBitmap(PdfiumCore.java:312)
W/System.err(13697): 	at com.github.barteksc.pdfviewer.PdfFile.renderPageBitmap(PdfFile.java:289)
W/System.err(13697): 	at com.github.barteksc.pdfviewer.RenderingHandler.proceed(RenderingHandler.java:109)
W/System.err(13697): 	at com.github.barteksc.pdfviewer.RenderingHandler.handleMessage(RenderingHandler.java:66)
W/System.err(13697): 	at android.os.Handler.dispatchMessage(Unknown Source:21)
W/System.err(13697): 	at android.os.Looper.loop(Unknown Source:207)
W/System.err(13697): 	at android.os.HandlerThread.run(Unknown Source:28)
E/BufferQueueProducer(13697): [SurfaceTexture-0-13697-0] dequeueBuffer: BufferQueue has been abandoned



Why does this happen just after installing the app and opening my first pdf.

I have a list of pdf from our db which are downloaded and displayed on the app. Once downloaded, by dio.download(pdf_url) then after I open it and confirm that the file exists, I open the file. 
But I have errors which happen on first launch. Could you have an idea why this happens?

**Comment by endigo** [comment]
> [#98 (comment)](https://github.com/endigo/flutter_pdfview/issues/98#issuecomment-676484431)
