### ISSUE TITLE
Pdf not loading in android 5.

### ISSUE THREAD

**Issue by razein97** [endigo/flutter_pdfview#101]
The pdf does not load in android 5 and below. Did not test with android 6, 8,10. Works with android 7, 9.
Proguard rule is also added.
Also tried  build option:
````
ndk {
                abiFilters 'armeabi-v7a'
            }
````
Error is probably due to architecture arm and arm64.
This is what is shown in debug:
```
W/linker  (13667): libc++_shared.so: unused DT entry: type 0x6ffffffe arg 0x2ab10
W/linker  (13667): libc++_shared.so: unused DT entry: type 0x6fffffff arg 0x3
W/linker  (13667): libmodpng.so: unused DT entry: type 0x6ffffef5 arg 0x436c
W/linker  (13667): libmodft2.so: unused DT entry: type 0x6ffffef5 arg 0x512c
W/linker  (13667): libmodpdfium.so: unused DT entry: type 0x6ffffef5 arg 0x596f4
W/linker  (13667): libjniPdfium.so: unused DT entry: type 0x6ffffffe arg 0x2290
W/linker  (13667): libjniPdfium.so: unused DT entry: type 0x6fffffff arg 0x3
D/com.shockwave.pdfium.PdfiumCore(13667): Starting PdfiumAndroid 1.9.0
I/Presentation(13667): Presentation is being immediately dismissed because the display metrics have changed since it was created.

```

**Comment by endigo** [comment]
Hello, android uses under the hood [barteksc/AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer/issues),
so you should go through native lib's resources like issues, stackoverflows etc.

**Comment by razein97** [comment]
> Hello, android uses under the hood [barteksc/AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer/issues),
> so you should go through native lib's resources like issues, stackoverflows etc.

@endigo I think this is not due to the native libs. While trying different plugins from from pub.dev I came across this plugin:
[https://github.com/scientifichackers/flutter_pdf_viewer](url)
It also uses the same base.
It works perfectly across all my test devices in release and debug mode.
The difference that I noticed was that this plugin launches an activity to show the pdf while your's does it inline in flutter.
It would awesome if you could take a look.
