### ISSUE TITLE
Support show Annotation on pdf

### ISSUE THREAD

**Issue by mouxhun** [endigo/flutter_pdfview#102]
on android, is there a way to support show annotation on pdf 
maybe give an option or just enable pdfView.enableAnnotationRendering(true)  directly?

**Comment by mouxhun** [comment]
ios does not have this problem, it show annotation correctly

**Comment by endigo** [comment]
@mouxhun Hey, can you make the change that contains your needs, and create PR?

**Comment by mouxhun** [comment]
With pleasure

**Comment by endigo** [comment]
@mouxhun release in 1.0.3+4. Thanks

**Comment by mouxhun** [comment]
You're welcome

**Comment by Sahmirzali** [comment]
@endigo @mouxhun How can i enable annotation ? could you help please ?

**Comment by endigo** [comment]
@Sahmirzali If you use the v1.0.3+4 and up, it is enabled by default.

**Comment by Sahmirzali** [comment]
@endigo i load pdf from asset. i can't select any text. but i'm sure text is selectable in pdf. i checked

**Comment by endigo** [comment]
@Sahmirzali annotation means an extra layer over the text layer. https://github.com/barteksc/AndroidPdfViewer maybe did not support text selection or I didn't enable it. If you find the issue, you could create new PR.

**Comment by Sahmirzali** [comment]
I want to know this package isn't support selection text ?

**Comment by endigo** [comment]
According to this issue, https://github.com/barteksc/AndroidPdfViewer/issues/95 text selection not supported by the native plugin

**Comment by Sahmirzali** [comment]
thanks for repy my question
