### ISSUE TITLE
onLinkHandle : how to stop open safari browser after click link inside PDF and just get value text http:// without open safari

### ISSUE THREAD

**Issue by suxma** [endigo/flutter_pdfview#105]
I use iPhone 11 iOS 13.3 for test my project.

I used onLinkHandle for handle value text link when click a link ( http://domain.com ) inside PDF File.
But always safari browser will open after click the link inside pdf file (for example link is "https://pub.dev". )

Can I stop open safari browser after click link inside PDF File, and just get text link with onLinkHandle without open safari browser?

**Comment by endigo** [comment]
In that case, you need to set not only onLinkHandle but also preventLinkNavigation to true.

**Comment by suxma** [comment]
Hi endigo, thank a lot, you help me..



Pada tanggal Kam, 1 Okt 2020 pukul 08.22 endigo <notifications@github.com>
menulis:
