### ISSUE TITLE
getCurrentPage,GetPageCount

### ISSUE THREAD

**Issue by Sahmirzali** [endigo/flutter_pdfview#107]
i want show currentpage/pagecount in appbar text title

i'm doing this like that ,  but this give me error : - > Instance of Future<int>.  how can i show currentpage/pagecount in appBar?

@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: FutureBuilder<PDFViewController>(
          future: _controller.future,
          builder: (context, AsyncSnapshot<PDFViewController> snapshot) {
            if (snapshot.hasData) {
              return Text(snapshot.data.getPageCount().toString()); // <-- I want to return this
            }
            return Text('??');
          },
        ),
      ),

**Comment by endigo** [comment]
You can use `onRender` and `onPageChange` on this situtation.

**Comment by huseynovali** [comment]
May you please give example? Because on Page Changed i use(activated) in Pdf. But i want to show in appBar

**Comment by Sahmirzali** [comment]
@endigo May you please give example? Because on Page Changed i use(activated) in PDFView class. But i want to show in appBar

my full code : https://pastebin.ubuntu.com/p/qNZQRfNbXb/

**Comment by endigo** [comment]
I believe this would work as you expected.

https://gist.github.com/endigo/c00a05aa440b9651d0d3249fddbbf0ac

**Comment by Sahmirzali** [comment]
@endigo  thanks for support
