### ISSUE TITLE
Black screen on OPPO phone

### ISSUE THREAD

**Issue by msaptomo** [endigo/flutter_pdfview#109]
there are some oppo devices that experience black screen when opening pdf files from url. how to fix it
![image](https://user-images.githubusercontent.com/35038331/96074225-5bbd8480-0ed2-11eb-992a-dab7be4e8af9.png)

**Comment by Nazmul1607081** [comment]
I have an app on playstore.Some user report me that new OPP COLOR OS phone show white screen when pdf reader open.
Any solution for this? I am in a great problem now.

**Comment by endigo** [comment]
There are issues which not resolved happen on only OPPO devices.
https://github.com/barteksc/AndroidPdfViewer/issues/613
https://github.com/barteksc/AndroidPdfViewer/issues/635

**Comment by Nazmul1607081** [comment]
@endigo Can we say that this is an issue with android?

**Comment by endigo** [comment]
@Nazmul1607081 No, it's an issue with [native library](https://github.com/barteksc/AndroidPdfViewer).

https://github.com/endigo/flutter_pdfview/issues/109#issuecomment-711463634
