### ISSUE TITLE
Duplicate Classes in Dependencies

### ISSUE THREAD

**Issue by tedchuang** [endigo/flutter_pdfview#11]
Dear Sir, this package may have a class name clash with another package:

  auto_size_text: ^1.1.2
  cupertino_icons: ^0.1.2
  flutter_pdfview: ^1.0.0+6
  flutter_swiper: ^1.1.6
  flutter_webview_plugin: ^0.3.5
  flutter_xlider: ^2.4.3
  folding_cell: ^0.1.2
  font_awesome_flutter: ^8.4.0
  http: ^0.12.0+2
  intl: ^0.15.8
  path_provider: ^1.1.0
  pull_to_refresh: ^1.3.7
  rxdart: ^0.22.0
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.2
  table_calendar: ^1.2.2
  vector_math: ^2.0.8

C:\Users\Ted\DEV\swan>flutter doctor -v
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.765], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at C:\flutter
    • Framework revision 7a4c33425d (5 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Ted\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.34.0)
    • VS Code at C:\Users\Ted\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.0.2

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

C:\Users\Ted\DEV\swan>flutter run --debug
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                              0.8s
Resolving dependencies...                                           2.7s
D8: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\4.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\5.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\6.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\7.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\8.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\9.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\10.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\11.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\12.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\13.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\14.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\15.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\16.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\17.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\18.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\19.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\20.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\21.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\22.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\23.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\24.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\25.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\26.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\27.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\28.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\29.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\30.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\31.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\32.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\33.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\34.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\35.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\36.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\37.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\55.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\60.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\65.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\70.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\75.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\80.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\85.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\90.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\95.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\100.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\105.jar, C:\Users\Ted\DEV\swan\build\app\intermediates\transforms\dexBuilder\debug\110.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         7.0s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1

**Comment by l-k22** [comment]
Can't you use the "as" feature to avoid conflicts, like this

```
import 'package:flutter_pdfview/flutter_pdfview.dart' as foo; //using "foo" as an example, can be anything
....
//then when you call the method
foo.PDFScreen(path: pathPDF)),

```

**Comment by tedchuang** [comment]
> Can't you use the "as" feature to avoid conflicts, like this
> 
> ```
> import 'package:flutter_pdfview/flutter_pdfview.dart' as foo; //using "foo" as an example, can be anything
> ....
> //then when you call the method
> foo.PDFScreen(path: pathPDF)),
> ```

Thank you, l-k22,

Still no go. I've commented out the entire codebase, commented out the import statement even.

As long as `flutter_pdfview: ^1.0.0+6` is in pubspec.yaml, it won't compile. When I comment out this depenency from pubspec.yaml, my app runs run like before.

In other words, my app compiles and runs fine. But when I added 1 line of code in pubspec.yaml, it won't build/run any more.

Thank you for your time.

**Comment by endigo** [comment]
@tedchuang hi, thanks for using.

What's your minSdkVersion?
Do you enable multidex?
Do you add proguard rules?

**Comment by tedchuang** [comment]
Thank you for attending to this report, endigo.

```
android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // SDK Level 22-25 used for Amazon only
        minSdkVersion 16
        targetSdkVersion 28
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

```

No changes to multidex or proguard rules. Project started with "flutter create" so default values are still there.

Thanks again.

**Comment by endigo** [comment]
Minimum required sdk version is 20.

**Comment by tedchuang** [comment]
Good morning, endigo,

I found the conflicting package - https://pub.dev/packages/flutter_webview_plugin

If you do a "flutter create newTestApp" and simply add these 2 packages in your pubspec without chaning anything in main.dart, you can see the error I'm talking about:

```
  flutter_pdfview: ^1.0.0+6
  flutter_webview_plugin: ^0.3.5

```

**Comment by ShashankSirmour** [comment]
I also phase this issue once I used to migrate to androidX and change my flutter channel to master now that is stable so just migrate to androidX and update your flutter version.
