### ISSUE TITLE
background color

### ISSUE THREAD

**Issue by Sahmirzali** [endigo/flutter_pdfview#111]
when i not use pdfview Colors.green is working 

```
Center(
            child: Container(
              color: Colors.green,
              height: MediaQuery.of(context).size.height * 0.75,
              width: MediaQuery.of(context).size.width,
```
When i use Pdfview Colors.green is not working :/ 

```
Center(
            child: Container(
              color: Colors.green,
              height: MediaQuery.of(context).size.height * 0.75,
              width: MediaQuery.of(context).size.width,
              child: PDFView(
                filePath: widget.pathblack,
                enableSwipe: true,
                swipeHorizontal: true,
                autoSpacing: true,

                pageFling: true,
                pageSnap: true,
                defaultPage: currentPage,
                fitPolicy: FitPolicy.BOTH,

                preventLinkNavigation:
                    true, // if set to true the link is handled in flutter
                onRender: (_pages) {
                  setState(() {
                    pages = _pages;
                    isReady = true;
                  });
                },
                fitEachPage: true,
                onError: (error) {
                  setState(() {
                    errorMessage = error.toString();
                  });
                  print(error.toString());
                },
                onPageError: (page, error) {
                  setState(() {
                    errorMessage = '$page: ${error.toString()}';
                  });
                  print('$page: ${error.toString()}');
                },
                onViewCreated: (PDFViewController pdfViewController) {
                  _controller.complete(pdfViewController);
                },
                onLinkHandler: (String uri) {
                  print('goto uri: $uri');
                },
                onPageChanged: (int page, int total) {
                  print('page change: $page/$total');

                  setState(() {
                    currentPage = page;
                  });
                },
              ),
            ),
          ),
```

Could you help me ?

**Comment by Sahmirzali** [comment]
![99b1d7ca-cb3a-4c5c-bac2-c916f493812e](https://user-images.githubusercontent.com/40922460/96310748-093ab000-1019-11eb-91f9-e57f9de94fda.jpg)
![9ebc80de-e4d1-4546-974e-f1c8115fa2e6](https://user-images.githubusercontent.com/40922460/96310752-0c35a080-1019-11eb-83ec-470b0aa3baa0.jpg)

**Comment by endigo** [comment]
hey, are there any logs?

**Comment by huseynovali** [comment]
@endigo no there isn't happened error, when i use pdf view with container, container color is white. Why?

**Comment by huseynovali** [comment]
@endigo for example could you please try in  your example project? Give background colour to container

**Comment by endigo** [comment]
Did you try to change the background color of PDF pages?

**Comment by huseynovali** [comment]
@endigo pdf page is white or blue it's not matter, i   want to pdf page will blue, then I want to container background colour make blue.

But color always white ((

**Comment by Sahmirzali** [comment]
@endigo when i `nightMode: true,`  the container color ( or background color ) happen black . :/ ? Could you please give information about that ? what can i do :/

**Comment by Sahmirzali** [comment]
@endigo  can you add background color property like this : https://github.com/arnaudelub/flutter_fullpdfview ?

**Comment by Sahmirzali** [comment]
@endigo Please add Colors.TRANSPARENT  background color

**Comment by endigo** [comment]
Hey guys it's currently not possible to change the background color because of a native library so-called [AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer).

When it comes to [this](https://github.com/endigo/flutter_pdfview/issues/111#issuecomment-710906024), a plugin uses a different fork of AndroidPdfViewer called [apv](https://github.com/arnaudelub/apv).
