### ISSUE TITLE
pdf disappear

### ISSUE THREAD

**Issue by sahmirzali** [endigo/flutter_pdfview#112]
When i close phone's navigate, pdf is disappear, how can i solve this problem ? why this problem is happen ? 

problem explain : https://youtu.be/Z_69P6dK81k

@endigo i also try in example project : https://youtu.be/pKo28y47WhY

**Comment by shahmirzali** [comment]
@endigo i'm sorry for upset you, but could you please answered my question ? 

@endigo Do you have this issue in your example ? could you please try (run) in your pc ?

**Comment by endigo** [comment]
@shahmirzali I did run my example project but I don't have any solution.

You could run through [AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer) source code.

If you find a solution, please create PR because there are issues that wait for very long time.

Thanks

**Comment by LuisDeLaValie** [comment]
I have the same problem I put a textfile to jump from page and from saparese, it also disappears when I flip the phone.

this is one of the messages that I get in both cases
     D / jniPdfium (8057): Destroy FPDF library

**Comment by jdeltoft** [comment]
I have this problem when I open a soft keyboard on another page.  I'm using another page to enter user info (name, phone etc).  The moment the soft keyboard is raised I get the "Destore FPDF library" message as well.  

See here for others with the same issue.  Their fix didn't help for me.

https://github.com/arnaudelub/flutter_fullpdfview/issues/2

**Comment by sahmirzali** [comment]
@LuisDeLaValie @jdeltoft  Did you find any solutions ?

**Comment by jdeltoft** [comment]
I moved to using a different pdf lib unfortunately.  @sahmirzali .  For my situation I got this one for the free community license:

  syncfusion_flutter_pdfviewer: ^18.4.42-beta

**Comment by raunak-many-ac** [comment]
syncfusion_flutter_pdfviewer doesn't have dark mode

**Comment by lcyper** [comment]
I found that this append when the pdf is resized.
Currently the package is using a vitual view, if we change to hibryd view it will fix? @endigo what do you think?

**Comment by raunak-many-ac** [comment]
@lcyper that's right.

My sense was we can do anything to reload either by reloading the widget or restarting the screen.

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA
