### ISSUE TITLE
Pdf not showing

### ISSUE THREAD

**Issue by MisterB2B** [endigo/flutter_pdfview#115]
When i try to load a 16MB pdf, It works but for my app I have to display some 1281.9MB pdf files. When i try to display them, the page is absolutely blank but the amount of pages works well... It just display nothing.

please help!

**Comment by endigo** [comment]
Hello, you should find more from the native library.

[https://github.com/barteksc/AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer)
