### ISSUE TITLE
Break PdfView when open Keyboard

### ISSUE THREAD

**Issue by Lykeosovandara** [endigo/flutter_pdfview#116]
**Describe the bug**
On an Android device when open the keyboard it causes pdf to show nothing.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select on TextField
2. Pdf view will show nothing

**Screenshots**
![Alt Text](https://i.imgur.com/pQgSVtC.gif)

**Smartphone (please complete the following information):**
 - Device: Huawei Nova 3i, Emulator Google Pixel 3a
 - OS: Android 
 - Version 10

**Comment by endigo** [comment]
Related to #9
