### ISSUE TITLE
PDFView Size on iOS Devices

### ISSUE THREAD

**Issue by Bentipa** [endigo/flutter_pdfview#117]
Hey,

if I embed the PDFView into a Scaffold body it only works on Android.
Android:
![image](https://user-images.githubusercontent.com/11789478/99944679-989f5580-2d73-11eb-8adc-50e0310352ea.png)
iOS:
![image](https://user-images.githubusercontent.com/11789478/99944715-a94fcb80-2d73-11eb-980a-1ed92df0c349.png)

In iOS the PDF is zoom-in from the beginning and is not fitting into the screen, is this behaviour somehow changeable?
I want to be able to zoom in, but also to see the whole PDF at once.

Thanks,
Benjamin

**Comment by computib** [comment]
Hi,

I have exactly the same problem.
Is there any workaround for this?

Thanks.

**Comment by Bentipa** [comment]
@computib 
I am using this one instead now: https://pub.dev/packages/pdf_viewer_plugin

**Comment by moazelsawaf** [comment]
The issue has been solved in the latest version of the package which is `1.2.3` by the time of this comment.

**Note:** You have to set the value of `autoSpacing` to `true` for the desired scale in the issue.
