### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by xylim666** [endigo/flutter_pdfview#119]
/Users/runner/.pub-cache/hosted/pub.dartlang.org/flutter_pdfview-1.0.3+7/ios/Classes/FlutterPDFView.m:172:12: error: implicit conversion of 'int' to 'id _Nullable' is disallowed with ARC
        result(true);

**Comment by endigo** [comment]
@daisuke310vvv Is it related to your changes?

@xylim666 You should downgrade to 1.0.3+6 until @daisuke310vvv fix that error.

**Comment by RamonCardosoBarbosa** [comment]
I am having the same problem for now.
