### ISSUE TITLE
File from url

### ISSUE THREAD

**Issue by benhaxe** [endigo/flutter_pdfview#12]
How do I open pdf file coming from url

**Comment by endigo** [comment]
Hi, this is not implemented.

First, you need to download PDF file.

**Comment by benhaxe** [comment]
Okay, is there a way out my initial plan is to load the pdf from the url. if no then how do I download the pdf

**Comment by tlueder** [comment]
You can use other plugins for that, like:

https://pub.dartlang.org/packages/dio

response = await dio.download("https://www.url.com/test.pdf", "local/path/test.pdf");

and then use the local path to load the pdf

**Comment by l-k22** [comment]
There is an example provided https://github.com/endigo/flutter_pdfview/blob/master/example/lib/main.dart

**Comment by ejabu** [comment]
> There is an example provided https://github.com/endigo/flutter_pdfview/blob/master/example/lib/main.dart

I tried it. Uncommenting this lines 

https://github.com/endigo/flutter_pdfview/blob/3c1a0c64948a483d43124ff17373eec4f9e9c581/example/lib/main.dart#L29-L35


but then the application crashed.

so I prefer using dio that @tlueder has described
