### ISSUE TITLE
Large Inverted Squares

### ISSUE THREAD

**Issue by crivano** [endigo/flutter_pdfview#123]
Page has some large inverted squares when nightMode is ommited or is set to 'false', as can be seen below:

![WhatsApp Image 2020-12-09 at 12 51 32](https://user-images.githubusercontent.com/4137623/101652746-5f2a4380-3a1d-11eb-95c7-d53827604e81.jpeg)

If I set nightMode to 'true' than it works as expected.

I'm using v1.0.4, and I tried with many other PDFs and they all have this same problem.

**Comment by crivano** [comment]
Changed minSdkVersion from 18 to 24 and the problem was fixed.

**Comment by AndreDrummer** [comment]
For me, this not solve the problem.
