### ISSUE TITLE
PDF not opening - No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument

### ISSUE THREAD

**Issue by rahul69x** [endigo/flutter_pdfview#124]
E/com.shockwave.pdfium.PdfiumCore( 8281): Native libraries failed to load - java.lang.UnsatisfiedLinkError: dlopen failed: library "libc++_shared.so" not found
W/Gralloc4( 8281): allocator 3.x is not supported
D/com.shockwave.pdfium.PdfiumCore( 8281): Starting PdfiumAndroid 1.9.0
E/kycloud.impuls( 8281): No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String) (tried Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument and Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String_2)
I/flutter ( 8281): java.lang.UnsatisfiedLinkError: No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String) (tried Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument and Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String_2)
W/kycloud.impuls( 8281): Accessing hidden method Ldalvik/system/CloseGuard;->close()V (greylist,core-platform-api, linking, allowed)

**Comment by gigihiski** [comment]
have you tried `flutter clean`?

**Comment by rahul69x** [comment]
Thank you. Perfect solution. Issue resolved. I have already done it.
