### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by l-k22** [endigo/flutter_pdfview#13]
Hi, I noticed the Night Mode is available to use on Android, I cannot see any information how to call this function.

Thanks

**Comment by endigo** [comment]
Hey, here is an example, just like other props pass it to PDFView widgets

``` dart
PDFView(
// other props
nightMode: true | false
),
```

**Comment by l-k22** [comment]
I wanted to add a toogle button to my bottom nav like so but this doesn't seem to work, my icon changes fine

```
PDFView(
// other props
nightMode: _nightMode
),
....
//method added to FloatingActionButton's onPressed 
toogleNightmode(bool toogle){
    switch(toogle){
      case true : 
        setState((){
           _nightMode = false;
           lightBulb = Icon(Icons.lightbulb_outline, color: Colors.white);
         });
         break;
        }
      case false: 
        setState((){
           _nightMode = true;
           lightBulb = Icon(Icons.lightbulb_outline, color: Colors.yellow);
         });
         break;
        }
    }
}
```

**Comment by endigo** [comment]
You should re-render the view.

**Comment by endigo** [comment]
AndroidPdfViewer plugin is not supported for instant changes in view.
Always require to redraw or re-render in view.

**Comment by l-k22** [comment]
ok thanks, is there a best way of doing this? I had thought about using the navigator to but this might not be a good idea.

**Comment by endigo** [comment]
That's not a good idea.
If you have some time, I will work on problems next week.

If you want to help develop this package, PRs are welcome.

Thanks.

**Comment by l-k22** [comment]
@endigo Hi, did you by any chance get an opportunity to work on this problem?
