### ISSUE TITLE
getWindow().addFlags(LayoutParams.FLAG_SECURE); show black screen in oppo devices

### ISSUE THREAD

**Issue by Zeyad-Amr** [endigo/flutter_pdfview#134]
I have a black screen after pdf file loading  and file not viewed in oppo devices
because of getWindow().addFlags(LayoutParams.FLAG_SECURE); showing black screen in oppo devices
any help please ??

**Comment by Zeyad-Amr** [comment]
anyone find a solution for this issue ??

**Comment by AbdOoSaed** [comment]
and try to use this [package ](https://pub.dev/packages/flutter_windowmanager)
https://pub.dev/packages/flutter_windowmanager
if u find the same issue 
please open a new issue in this [repo](https://github.com/adaptant-labs/flutter_windowmanager)

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA
