### ISSUE TITLE
 flutter_full_pdf_viewer: ^1.0.6   not working on IOS real device 

### ISSUE THREAD

**Issue by Adityapalmzn12** [endigo/flutter_pdfview#139]
I am Getting error when i open a pdf by using this library .please check as given below  the error when run on real device (iphone SE new 2020).

Error-
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: FileSystemException: Cannot open file, path = '/var/mobile/Containers/Data/Application/24CF747D-FDA6-4DBA-88FA-6777683D92ED/Documents10511001_1.pdf' (OS Error: Operation not permitted, errno = 1)

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA
