### ISSUE TITLE
Application Crash if the open file is not PDF

### ISSUE THREAD

**Issue by ShashankSirmour** [endigo/flutter_pdfview#14]
if somehow in Flutter_pdfview check the opened file is pdf or not and give response then it will not crash

**Comment by endigo** [comment]
Hello, you can check using built-in method from ```dart:io```

```dart
import "dart:io"

String path = "filepath.pdf";

File(path).exists();
```

**Comment by ShashankSirmour** [comment]
i mean if the file is epub or another format it crashes all the application   so I think its better to check  the file format in package side

**Comment by ShashankSirmour** [comment]
I tried all the pdf packages they are not crashing but they are not better than this package  this package is really very beautiful and highly customizable  thank you for the great package

**Comment by ShashankSirmour** [comment]
> Hello, you can check using built-in method from `dart:io`
> 
> ```dart
> import "dart:io"
> 
> String path = "filepath.pdf";
> 
> File(path).exists();
> ```

i mean format like epub or other it crashes when the file is not pdf

**Comment by l-k22** [comment]
you can implement your own file extension check
https://api.flutter.dev/flutter/package-path_path/extension.html

**Comment by endigo** [comment]
@l-k22 Thank you for your suggestion. Feel free to create PR.

**Comment by l-k22** [comment]
> @l-k22 Thank you for your suggestion. Feel free to create PR.

I made a fork and edited the example to to include a simple snackbar that prevents a non pdf file being opened. 
I decided to only do edit the example as the developer may have their own design specification on how to handle alerts (an alert dialog might be too intrusive).
PR submitted.
