### ISSUE TITLE
Flutter_pdfview is deprecated

### ISSUE THREAD

**Issue by mibkvr** [endigo/flutter_pdfview#146]
The plugin `flutter_pdfview` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future
release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by PcolBP** [comment]
In next stable release probably plugin won't work any more.

**Comment by mibkvr** [comment]
I know. Can't you fix that?

**Comment by PcolBP** [comment]
#147 Merged, can be closed.

**Comment by mibkvr** [comment]
Thank you
