### ISSUE TITLE
application crash when Enabling Proguard

### ISSUE THREAD

**Issue by ShashankSirmour** [endigo/flutter_pdfview#15]
Enabling Proguard  crash the application when trying to open pdf

**Comment by l-k22** [comment]
share full error log

**Comment by ShashankSirmour** [comment]
actually, there is no error  application is just shut down while opening pdf - when enabling  application  Proguard is enabled

**Comment by endigo** [comment]
Hi,

Please share flutter sdk version

**Comment by ShashankSirmour** [comment]
Flutter 1.7.5-pre.28 • channel master • https://github.com/flutter/flutter.git
Framework • revision 7d95e8e0c1 (9 days ago) • 2019-06-18 11:32:13 -0700
Engine • revision 05c034e5bb
Tools • Dart 2.4.0

**Comment by endigo** [comment]
This issue might be related to https://github.com/barteksc/AndroidPdfViewer/issues/480 and https://github.com/barteksc/AndroidPdfViewer/issues/491

**Comment by ShashankSirmour** [comment]
thank you very much thank you @endigo 👍  adding this to proguard resolves my issue :

-keep class com.shockwave.**
-keepclassmembers class com.shockwave.** { *; }
