### ISSUE TITLE
Not able to show well fitted PDF at iOS, but OK for Android

### ISSUE THREAD

**Issue by DmitriyYakovlev** [endigo/flutter_pdfview#150]
I have such set up:

PDFView(
            filePath: widget.path,
            enableSwipe: true,
            swipeHorizontal: false,
            autoSpacing: false,
            pageFling: true,
            pageSnap: true,
            defaultPage: currentPage,
            fitPolicy: FitPolicy.BOTH,
            preventLinkNavigation: false,
            // if set to true the link is handled in flutter
)

And it works ok on Android, the page is well fitted, space between pages not visible.
![photo_2021-09-08_18-54-02](https://user-images.githubusercontent.com/5854471/132544087-19850f08-3314-40ee-92fe-ac4c51146f76.jpg)

But at iOS is not the same, I need the same as on android

![photo_2021-09-08_18-50-48](https://user-images.githubusercontent.com/5854471/132544147-71c1dbc9-2038-426e-979b-233f98fb557a.jpg)

**Comment by ZXERSTON** [comment]
I am facing the same issue as you. I think the culprit is autofacing:false, I removed it and ios was showing okay and android is showing okay. However, once added, android view is okay but ios one is zoomed in when opened.

**Comment by DmitriyYakovlev** [comment]
> I am facing the same issue as you. I think the culprit is autofacing:false, I removed it and ios was showing okay and android is showing okay. However, once added, android view is okay but ios one is zoomed in when opened.
> 
> DId you find the solution?

unfortunatelly, no

**Comment by moazelsawaf** [comment]
The issue has been solved in the latest version of the package which is `1.2.3` by the time of this comment.

**Note:** You have to set the value of `autoSpacing` to `true` for the desired scale in the issue.

**Comment by techouse** [comment]
In my experience it's best to set it like so

```dart
PDFView(
  autoSpacing: Platform.isIOS,
  // stuff ...
);
```
