### ISSUE TITLE
The plugin `flutter_pdfview` use a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by sebastianbuechler** [endigo/flutter_pdfview#151]
The plugin `flutter_pdfview` use a deprecated version of the Android embedding.

To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.

If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by PcolBP** [comment]
Which version of plugin do you use? Wasnt it fixed in 1.2.0?

**Comment by sebastianbuechler** [comment]
The warning came with 1.0.4 and you're right, it was fixed in 1.2.0. Thanks!
