### ISSUE TITLE
Error during run android

### ISSUE THREAD

**Issue by AlirezaDaryani** [endigo/flutter_pdfview#159]
I can't make release anymore and below log occur when build android:

`* What went wrong:
A problem occurred configuring project ':flutter_pdfview'.
> Could not resolve all artifacts for configuration ':flutter_pdfview:classpath'.
   > Could not find com.android.tools.build:gradle:3.2.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom
       - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom
     Required by:
         project :flutter_pdfview`

**Comment by The-Redhat** [comment]
What is your build gradle version (`com.android.tools.build:gradle:4.1.3`) specified in `android/build.gradle` ?

**Comment by AlirezaDaryani** [comment]
`classpath 'com.android.tools.build:gradle:4.1.2'`

**Comment by AlirezaDaryani** [comment]
Actually I found the problem, its not your bug and refer to my network.
Thanks
