### ISSUE TITLE
The library increased the weight of the APK 

### ISSUE THREAD

**Issue by flutteresbolivia** [endigo/flutter_pdfview#163]
The library increased the weight of the APK by + 18MB.

Before it weighed 27MB, now 45MB.

I do not know if it will affect production for download that was previously 10MB.

and I do not know if it will go up to more.

This is normal?

![Screenshot_2](https://user-images.githubusercontent.com/67565934/144720693-33ef3508-6bfd-4423-a531-d3909f007fae.png)

![Screenshot_3](https://user-images.githubusercontent.com/67565934/144720730-cb88ba36-6875-45f8-b7e8-0d41df45bd37.png)

**Comment by flutteresbolivia** [comment]
@endigo  help pls

**Comment by endigo** [comment]
@flutteresbolivia Hello, sorry for the late response.

This package depends on [AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer).

[Here is guide from AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer#why-resulting-apk-is-so-big)

**Comment by flutteresbolivia** [comment]
> @flutteresbolivia Hello, sorry for the late response.
> 
> This package depends on [AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer).
> 
> [Here is guide from AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer#why-resulting-apk-is-so-big)

Thanks!!!
