### ISSUE TITLE
[iOS] PDF wrong initial zoom and no horizontal swipe

### ISSUE THREAD

**Issue by deakjahn** [endigo/flutter_pdfview#166]
With version 1.2.1, I have the following:

        defaultPage: _current,
        enableSwipe: true,
        swipeHorizontal: true,
        autoSpacing: true,
        pageFling: false,
        pageSnap: false,
        fitPolicy: FitPolicy.BOTH,

Android works all right, iOS not. First, the PDF opens zoomed in (this is discussed in https://github.com/endigo/flutter_pdfview/issues/150 but the workaround mentioned doesn't seem to work any more). Second, there's no horizontal swipe between the pages.

**Comment by Taron133** [comment]
Temp solution: Change page after ViewCreated:

`Widget getPDFView(UniqueKey pdfKey) {
    return PDFView(
      key: pdfKey,
      filePath: pdfPath,
      enableSwipe: true,
      swipeHorizontal: true,
      autoSpacing: true,
      pageFling: true,
      defaultPage: 1/*currentPage!*/,`

`onViewCreated: (PDFViewController pdfViewController) {
       _controller = pdfViewController;
        Future.delayed(const Duration(milliseconds: 50), () {
          _controller!.setPage(0);
        });
      },`

**Comment by moazelsawaf** [comment]
The issue has been solved in the latest version of the package which is `1.2.3` by the time of this comment.

**Note:** You have to set the value of `autoSpacing` to `true` for the desired scale in the issue.
