### ISSUE TITLE
Purchase "Search functionality" feature possible?

### ISSUE THREAD

**Issue by GSORF** [endigo/flutter_pdfview#179]
Hi @endigo,

Thank you for the awesome flutter plugin, it works like a charm in my iOS simulator (couldn't test it on a real device yet, hope I will not have the same issue like a few other users).

I am currently developing an app for a client and presented him the first prototype draft which uses your PDF API. The client asked me if it is possible to search for keywords in the pdf view so that these get highlighted (similar to how it works in Adobe Acrobat Reader when you press "CTRL + F"). I see that this feature is on your _Future Plans_ list.

My question is: In case I can acquire a bit more funding from my client, is it possible to fund a specific feature by buying you _"several coffees"_? I would love to support your work financially and consequently improve the quality for everyone else using it. In this early phase I just want to know if this is possible at all.

Thanks for your answer in advance and kind regards!

**Comment by GSORF** [comment]
Unfortunately there is no answer to my question since three months.
Therefore, I have started to implement the functionality myself. It is not perfect yet, but at least one can now search inside a pdf document.

In case anyone is in the same situation: What I did is the following:

1. Fork this repository
2. Apply the pull request from [Taron133:SearchText_iOS](https://github.com/Taron133/flutter_pdfview/tree/SearchText_iOS)
3. In your flutter project: Do not add "flutter_pdf" from the official source but use your own git repository (that was actually the key to the implementation! I was not aware of this method before)
4. Inside the app: After loading a pdf file into the viewer, loop through each page and extract the document string using "getStringAt(page_id)"
5. In your search function: Compare the query string with the document string and store your matches. Then display them to the user (I am currently merely displaying the page number and a substring where the query string was found. Users can jump to the page by clicking on the search result)

This is not optimal yet, but at least a beginning. A big "thank you" goes to @Taron133 for implementing the string extraction feature. Highlighting the found text in the PDFViewer would be nice now, which - to my understanding - is not yet implemented.

Reading the documentation of PDFKit (iOS only) though, it appears to be possible to add this, compare https://www.pdftron.com/blog/ios/how-to-add-annotations-using-swift-and-pdfkit/

Since I have never worked with the swift programming language I will need some time to get my head around this, but it doesnt seem to be very difficult. If I will manage to implement highlighting, I will post my solution here as well.

Kind regards,
Adam

**Comment by dupuchba** [comment]
Working with PDF is hard, if you look at the AppStore, PDF applications are often on the top most downloaded apps. In this plugin case, it creates a UiKitView which is still alpha on Flutter. Yes PDFKit provides by default search but it does not guarantees if it would work properly on UiKitView.
There is an other option to build PDF which is to render them via Flutters `Texture` layer, but then it's like if you draw images for each pages (no search as far as I can tell).

I think best dev XP would be to develop a renderer in pure Dart but it would literally take years (full-time). With my co-worker we've been there working with PDFs and the spec is just too big. That's basically why there are still proprietary APIs in this field. 
Anyway if you need high quality PDF renderer with the ability to customise everything, there might be some lib out there but I doubt it, otherwise you can try to help like you did !

**Comment by mirkancal** [comment]
https://user-images.githubusercontent.com/26160059/228448213-64eb043c-b0f9-4a41-af2a-2e5e20f348f7.mov

I've added for iOS, let me know what you guys think @endigo 
https://github.com/mirkancal/flutter_pdfview/commit/49638d9084622f2816b7c3c92b394750dc9b7701

**Comment by GSORF** [comment]
Thank you @mirkancal for your great work! This looks awesome.
And thank you, @dupuchba for your detailed feedback on this idea.

Due to time restrictions I had to move from flutter_pdfview to syncfusion_pdf (https://pub.dev/packages/syncfusion_flutter_pdf). I will therefore close this issue.

Kind regards,
Adam

**Comment by mvukojicic** [comment]
@mirkancal  Hey bro, nice work out there, did you by any chance make a solution to jump to a specific page when searching the text?

**Comment by mirkancal** [comment]
@mvukojicic It's jumping to page but when there are lot of results from the same search keywords, it's pretty slow and freezes. I need to convert search results to stream or something. Also I couldn't find anything for Android.

**Comment by mvukojicic** [comment]
@mirkancal Can you please point me to the part of the code and logic for jumping to searched words?

**Comment by mirkancal** [comment]
@mvukojicic it's pdfview.go

https://github.com/mirkancal/alh_pdf_view/commit/cf2d3a6568ba983d6b11790922d0dffee917fae1#diff-1e42e7adbd1ae9be1a09a5f2c6865f0147bd8a042d7428db83a0573f769e783bR338-R343

**Comment by mvukojicic** [comment]
@mirkancal bro you are the king, thank you so much!
