### ISSUE TITLE
Byte array instead of file path

### ISSUE THREAD

**Issue by deakjahn** [endigo/flutter_pdfview#18]
Considering that the viewer also accepts a byte array in addition to a path (pdfView.FromBytes), it might be added as another way to start the widget. This would remove the need to copy from the Flutter assets to the platform assets as shown in the example.

**Comment by endigo** [comment]
From my perspective, it is the way to implement byte array option,

https://github.com/endigo/flutter_pdfview/blob/master/example/lib/main.dart#L59

**Comment by deakjahn** [comment]
No, you save the file. There is no need to save the file at all. Just pass the Uint8List to the platform side and use it directly. I do it in a modified copy of your plugin and it works just fine. :-)

**Comment by endigo** [comment]
Hi, so you can create pull request, we would love to see. :)

**Comment by deakjahn** [comment]
Well, yes, but to tell you frankly, I did remove the filename part because I don't need it at all. And for a pull request, I would need to set up Git and whatever. Would it help you if I just copied the few lines and ideas here and would leave it up to you to decide what to do with them instead of a PR? :-))

**Comment by deakjahn** [comment]
OK, I gave it a try. I hope it goes smoothly. I re-did my local version according to your current one and it seems to work all right for me.
