### ISSUE TITLE
After i use flutter_pdfview,the apk size is too large

### ISSUE THREAD

**Issue by yaochangliang159** [endigo/flutter_pdfview#183]
i create a new project,and i build apk,the  apk size is 16.1MB,
and then,i add flutter_pdfview:1.2.1 into pubspec.yaml, build apk,the apk size is 35.4MB
your library size is 19MB，
can you optimization this???
<img width="1553" alt="111" src="https://user-images.githubusercontent.com/13497352/167324458-9f458ff1-c149-49ea-9381-84755ebf5683.png">
<img width="1572" alt="2222" src="https://user-images.githubusercontent.com/13497352/167324477-5000395f-7b65-4470-880c-bce679457f12.png">

**Comment by endigo** [comment]
There is nothing to do with dart/flutter. It about the [plugin](https://github.com/barteksc/AndroidPdfViewer).

There are a bunch of issues
I hope you can find solutions from [here](https://github.com/barteksc/AndroidPdfViewer/issues?q=is%3Aissue+apk+size)
e.g
[https://github.com/barteksc/AndroidPdfViewer/issues/664](https://github.com/barteksc/AndroidPdfViewer/issues/664)

**Comment by yaochangliang159** [comment]
i understand,thank you
