### ISSUE TITLE
Does it support Remote pdf url?

### ISSUE THREAD

**Issue by subinsuresh** [endigo/flutter_pdfview#196]

**Comment by endigo** [comment]
It does support

**Comment by baptistesx** [comment]
Hey,

trying a remote url for a pdf file as you said it does support => filePath: https://pdfobject.com/pdf/sample.pdf

No error but white screen.

Do I miss anything?

Thanks in advance!

**Comment by 9clg6** [comment]
Same here, any solution ? @baptistesx
