### ISSUE TITLE
set page

### ISSUE THREAD

**Issue by lastlink** [endigo/flutter_pdfview#2]
I noticed you have an onpagechange, could you also add a setpage function for android and ios. Thank you!

**Comment by endigo** [comment]
Here is example.
https://github.com/endigo/flutter_pdfview/blob/master/example/lib/main.dart#L109

**Comment by lastlink** [comment]
great could you update the options table in the readme to include it? thanks!

**Comment by endigo** [comment]
Sure

**Comment by endigo** [comment]
@lastlink updated in Readme.md
