### ISSUE TITLE
Android repository can not get resolved

### ISSUE THREAD

**Issue by oorfalimak** [endigo/flutter_pdfview#205]
Hello,
Flutter build is failing with error "Could not resolve com.github.barteksc:android-pdf-viewer:3.2.0-beta.1", 
this dependency must be changed. 

There is an open pull request to solve this problem : https://github.com/endigo/flutter_pdfview/pull/202

**Comment by GitHelge** [comment]
I hope the maintainer of flutter_pdfview is reading this. Do you have a workaround for the meantime?

**Comment by GitHelge** [comment]
I know the linked PR is merged but the issue could be caused by jitpack directly. https://github.com/jitpack/jitpack.io/issues/5239

**Comment by oorfalimak** [comment]
After updating to version 1.2.5 the problem is solved, thanks.
