### ISSUE TITLE
Execution failed for task ':app:checkDebugDuplicateClasses'.

### ISSUE THREAD

**Issue by stephane-couget** [endigo/flutter_pdfview#208]
Hello,

I encounter this error which disables the flutter_pdfview plugin: ^1.2.1 until flutter_pdfview version: ^1.2.5

It started when I wanted to upgrade from 1.2.1 to 1.2.5
Going back to 1.2.1 didn't change anything.
I deleted .pub-cache
performed flutter clean

I don't use XCode except AS and my mobile only project is Android only.

Any compilation fails. I have to disable the plugin in my project to be able to debug my works.

An idea ?

`[✓] Flutter (Channel stable, 3.3.3, on macOS 12.6 21G115 darwin-x64, locale fr-FR)
    • Flutter version 3.3.3 on channel stable at /Users/stephanecouget/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (il y a 6 jours), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/stephanecouget/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    ! CocoaPods 1.9.3 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • SM T970 (mobile) • R52R40AJJ6R • android-arm64  • Android 12 (API 32)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 106.0.5249.91

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
`

------------------------ FAILURE

`FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:checkDebugDuplicateClasses'.
[        ] > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
[        ]    > Duplicate class android.support.v4.app.INotificationSideChannel found in modules core-1.8.0-runtime (androidx.core:core:1.8.0) and support-compat-27.1.1-runtime `(com.android.support:support-compat:27.1.1)`

[failure.pdf](https://github.com/endigo/flutter_pdfview/files/9705074/failure.pdf)

Best regards,

**Comment by endigo** [comment]
I think it is not related to this package. Please refer AndroidPdfViewer
