### ISSUE TITLE
password property is bool in dart api, but string in IOS and Android plugins

### ISSUE THREAD

**Issue by ormrodjames** [endigo/flutter_pdfview#21]
By far and away the best Flutter PDF plugin, thanks!

Unfortunately there is a gremlin in the definition of the password property in PDFView - it's a bool, but I think it should be a string? (At least, I hope it should be a string since I need to be able to unlock programatically without the user having to know the password...)

On Android I get "java.lang.Boolean cannot be cast to java.lang.String", and I see password is a string in both the IOS and Android plugins.

**Comment by endigo** [comment]
FIxed in 1.0.0+8
