### ISSUE TITLE
PDFView generated half zoomed view

### ISSUE THREAD

**Issue by charlieforward9** [endigo/flutter_pdfview#210]
I am expecting the view to return a fully visible page, however, it returns the PDF zoomed in. This degrades UX and requires more interaction than necessary for my use case.

Expected vs Actual :
![IMG_3592](https://user-images.githubusercontent.com/62311337/198505897-e4b050f9-2ef8-42ef-8b9e-c5e450f8fa49.jpg)

Actual: 
![IMG_3593](https://user-images.githubusercontent.com/62311337/198505963-e3a02c17-afd0-4800-8d0b-a21019dd1cb6.PNG)

**Comment by charlieforward9** [comment]
Note: it appears that #173 addresses this for Andriod, but not yet for iOS. Awaiting a response from the contributor.

**Comment by dhcracchiolo** [comment]
+1

**Comment by dhcracchiolo** [comment]
Solved here:
https://github.com/endigo/flutter_pdfview/issues/150#issuecomment-1203996104

**Comment by charlieforward9** [comment]
Thank you @dhcracchiolo , removing `autoSpacing = false` is all I had to do!
