### ISSUE TITLE
Release version not working

### ISSUE THREAD

**Issue by zatovagul** [endigo/flutter_pdfview#212]
When I run debug build this library works without any problems. When I run release build on Android, PdfView not working, but there is no any logs. I tried also flutter run --release -v, and I didn't noticed any errors with PdfView problem.

Do you know how to fix it?

**Comment by shinxxxxwon** [comment]
I'm having the same problem. did you solve it?

**Comment by endigo** [comment]
Hey guys thanks for using this library. The library's Android side depends on [AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer), so you guys look through the issues of AndroidPdfViewer GitHub.

Thanks

**Comment by shinxxxxwon** [comment]
@endigo Thanks for sharing the package.

There is no problem displaying the PDF in debug and release mode. But i think the pdfData changes according to options. The problem is that the pdf data is changed using `ValueKey()` in debug mode, but not in release. Is there any way to solve this problem??
