### ISSUE TITLE
how to update PDFView filePath or pdfData?

### ISSUE THREAD

**Issue by shinxxxxwon** [endigo/flutter_pdfview#216]
In PDFView Widget, the pdf is displayed on the screen as the pdfData variable. The first pdf is displayed well, but later the pdf may be changed. Is there a way to update the UI with the changed pdf when the pdf changes?

**Comment by shinxxxxwon** [comment]
In debug mode, it is updated normally, but in release mode, pdf is not changed as a key value.
```
return PDFView(
                key: ValueKey(pdf.keyCount),
                // key: widget.key!,
                // filePath: context.watch<PDFProvider>().strPdfPath!,
                pdfData: pdf.uinPdfData!,
                enableSwipe: true,
                swipeHorizontal: true,
                autoSpacing: false,
                pageFling: false,
                defaultPage: 0,
                onRender: (_pages) {
                  setState(() {
                    isReady = true;
                  });
                },
                onError: (error) {
                  print(error.toString());
                },
                onPageError: (page, error) {
                  print('$page: ${error.toString()}');
                },
                // onViewCreated: (PDFViewController pdfViewController) {
                //   _controller.complete(pdfViewController);
                // },
                onPageChanged: (int? page, int? total) {
                  setState(() {
                    nPageIndex = page! + 1;
                  });
                },
              );
```

**Comment by shinxxxxwon** [comment]
If you change the page after changing `pdfData` in `release` mode, `pdf` will be updated. Is there a way to update the `PdfView` widget when `pdfData` changes?

**Comment by loginleng** [comment]
Simple use of 'Visiblity'；
`ValueNotifier<String?> pdfUrl = ValueNotifier(null);`
`initState(){
    super.initState();
    pdfUrl.value = widget.data[0]['url'];
    pdfUrl.addListener(() {
      setState(() {
        showPdf = false;
      });
      WidgetsBinding.instance!.addPostFrameCallback((_) {
        setState(() {
          showPdf = true;
        });
      });
    });
  }`
`Visibility(
                visible: showPdf,
                child: PDF(
                  swipeHorizontal: true,
                ).cachedFromUrl(
                  pdfUrl.value!,
                ),
              )`
