### ISSUE TITLE
Pdf is creating error on ios but proper working on android

### ISSUE THREAD

**Issue by iusamaashraf** [endigo/flutter_pdfview#219]
I have implemented your package and it works fine on android phone but when we open in physical iPhone device then i get the path of pdf's but didn't open that it creates error
 **"unhandled exception: filesystemexception: cannot open file, path .... (OS no such file or directory errno=1)"**

**Comment by AyatAliev** [comment]
I have the same error, could you find a solution?

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA

**Comment by iusamaashraf** [comment]
> I have the same error, could you find a solution?

yea i have found it's solution actually we need to set the platform.ios for this
