### ISSUE TITLE
Bump android-pdf-viewer to update to Androidx

### ISSUE THREAD

**Issue by asaarnak** [endigo/flutter_pdfview#220]
https://github.com/mhiew/AndroidPdfViewer#320-beta3

**Comment by asaarnak** [comment]
@endigo
Can you take a look please.
Thanks!

**Comment by asaarnak** [comment]
@endigo Why it was downgraded to beta.2 ?

**Comment by endigo** [comment]
@asaarnak It throws some error. Something like this #231

**Comment by asaarnak** [comment]
I think we should still update to beta.3 or we can't support AndroidX and disable jetifier.
They need to update kotlin libs. Are you sure beta.3 created #231 issue?
https://github.com/flutter/flutter/issues/122755
https://stackoverflow.com/questions/75752269/fatal-error-kotlin-stdlib-jdk7-1-5-30-pom21-content-is-not-allowed-in-prolog

**Comment by agacemi** [comment]
@endigo We also waiting for pdfviewer working without jetifier.. I would be great to have new version of flutter_pdfviewer that allows disabling jetifier on Android

**Comment by endigo** [comment]
@agacemi  @asaarnak I released 1.3.0 today. Please notify me. Is it properly?

**Comment by agacemi** [comment]
Thank you @endigo with the new release, we no longer need jetifier..

I take this opportunity to find out if "muPdf" will soon be integrated to relplace AndroidPdfViewer as announced in the plan

**Comment by asaarnak** [comment]
@endigo We switched over to `printing` dependency to preview pdfs, but previously we used dependency_override and it worked properly.
