### ISSUE TITLE
Enhancement: Add a page flip effect

### ISSUE THREAD

**Issue by maxmitz** [endigo/flutter_pdfview#222]
It would be nice to have a page-flip effect when you go from one page to another like this:

![bUnCQ](https://user-images.githubusercontent.com/72440045/213138232-21915e01-bc8d-4b0b-91fa-2998e361f34e.jpg)

(The picture is from [StackOverflow](https://stackoverflow.com/questions/73519311/how-to-make-pdf-page-flip-effect-in-flutter))

**Comment by endigo** [comment]
Simply it is not possible. Thanks
