### ISSUE TITLE
 'Uint8List' isn't a type. on 1.2.6

### ISSUE THREAD

**Issue by xrandy00** [endigo/flutter_pdfview#228]
Hi, after latest update we got this error in our CI pipeline.

**/opt/hostedtoolcache/flutter_sdk/3.0.5/linux/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_pdfview-1.2.6/lib/flutter_pdfview.dart:68:9: Error: 'Uint8List' isn't a type.**

The issue is also reproducible locally. I cloned the repo, did pub get and analyzer is unable to find the dependency.
It is caused by [this commit.](https://github.com/endigo/flutter_pdfview/commit/1b01190f953ff1ccf67e2927d856ec97dd989626) 
Might be connected to Flutter version.

```
flutter doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-CZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.76.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

![image](https://user-images.githubusercontent.com/25846048/225061101-9d75e752-6b45-4758-b65f-d530f6ccdb04.png)

With latest stable flutter (3.7.0) there is no issue and everything works fine. 
We can solve this by locking the dependency version to 1.2.5, but consider reverting it, as patch number was increased with a breaking change, which is against semver.

**Comment by endigo** [comment]
I had to close it. You have to stick with latest possible Flutter versions.
