### ISSUE TITLE
onError does not work, causing app to crash upon loading a corrupted file

### ISSUE THREAD

**Issue by MaskyS** [endigo/flutter_pdfview#23]
Upon opening a corrupted file, the app crashes. the callback fed to the onError parameter (introduced by @santiihoyos in #22) is never executed. 

Steps to reproduce: 

Download example app. Replace `assets/demo.pdf` by 
[corrupted.pdf](https://github.com/endigo/flutter_pdfview/files/3492476/corrupted.pdf)

Run app. Try to open pdf.

**Comment by MaskyS** [comment]
I think the issue is that the error is never propagated to the dart side. This plugin has working error handling, https://github.com/pycampers/flutter_pdf_viewer/commit/bc67facfa13fd394341ba3c738535f2efbe09207 but it is not inline. 

The implementation also seems more complex.

**Comment by GENL** [comment]
Same problem, it's very strange. Because of this, I can not check the password of the file. If the user enters the wrong PDF password, the application crashes.

**Comment by r4faelferreir4** [comment]
Same here, getting 
java.lang.IllegalArgumentException: Unsupported value: java.io.IOException: cannot create document: File not in PDF format or corrupted.

And app crashes

**Comment by gauravsingla05** [comment]
> Same here, getting
> java.lang.IllegalArgumentException: Unsupported value: java.io.IOException: cannot create document: File not in PDF format or corrupted.
> 
> And app crashes

This same happens to me as well

**Comment by MaskyS** [comment]
@endigo This has been fixed in #36! Huge thanks to @phamnhuvu-dev <3
