### ISSUE TITLE
[Fatal Error] kotlin-stdlib-jdk7-1.5.30.pom:2:1: Content is not allowed in prolog.

### ISSUE THREAD

**Issue by abudestiny** [endigo/flutter_pdfview#231]
[Fatal Error] kotlin-stdlib-jdk7-1.5.30.pom:2:1: Content is not allowed in prolog.
[Fatal Error] kotlin-stdlib-jdk7-1.5.30.pom:2:1: Content is not allowed in prolog.
[Fatal Error] kotlin-stdlib-jdk7-1.5.30.pom:2:1: Content is not allowed in prolog.
[Fatal Error] kotlin-stdlib-jdk7-1.5.30.pom:2:1: Content is not allowed in prolog.
[Fatal Error] kotlin-stdlib-jdk7-1.5.30.pom:2:1: Content is not allowed in prolog.
[Fatal Error] kotlin-stdlib-jdk7-1.5.30.pom:2:1: Content is not allowed in prolog.
[Fatal Error] kotlin-stdlib-jdk7-1.5.30.pom:2:1: Content is not allowed in prolog.
[Fatal Error] kotlin-stdlib-jdk7-1.5.30.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_pdfview:generateDebugRFile'.
> Could not resolve all files for configuration ':flutter_pdfview:debugCompileClasspath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.30.
     Required by:
         project :flutter_pdfview > org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30
      > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.30.
         > Could not parse POM https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.5.30/kotlin-stdlib-jdk7-1.5.30.pom
            > Content is not allowed in prolog.
      > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.30.
         > Could not parse POM https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.5.30/kotlin-stdlib-jdk7-1.5.30.pom
            > Content is not allowed in prolog.
      > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.30.
         > Could not parse POM https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.5.30/kotlin-stdlib-jdk7-1.5.30.pom
            > Content is not allowed in prolog.
      > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.30.
         > Could not parse POM https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.5.30/kotlin-stdlib-jdk7-1.5.30.pom
            > Content is not allowed in prolog.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 7s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by endigo** [comment]
I think this is not related to this plugin.

**Comment by asaarnak** [comment]
@abudestiny Did you manage to fix this error ?

**Comment by abudestiny** [comment]
Yes

**Comment by asaarnak** [comment]
@abudestiny How?

**Comment by asaarnak** [comment]
@endigo This is propably not related to beta.3 update.
