### ISSUE TITLE
Plugin Makes Build APK Too Large

### ISSUE THREAD

**Issue by TristanGrobler** [endigo/flutter_pdfview#232]
Before Adding:
![Screenshot 2023-03-17 at 14 11 10](https://user-images.githubusercontent.com/70268395/225900762-cf4fcfbb-ae11-4cde-806e-d92ef53cd805.png)

After Adding:
![Screenshot 2023-03-17 at 14 06 36](https://user-images.githubusercontent.com/70268395/225899903-996b971d-e2ba-4712-8e28-88c1b1ae7df8.png)

As can be seen, after adding the package, the release apk size is around 80mb. When I remove it and add another package, the release size is around 35mb. 

Each time I run a "flutter pub clean && flutter pub get && flutter build apk" between any changes.

To recreate this, create a new flutter project, add the dependency and run the above command in terminal.

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA

**Comment by endigo** [comment]
Hello, you should use app bundle, not APK.
https://docs.flutter.dev/deployment/android#build-an-app-bundle

This will help you to reduce the final APK size.
