### ISSUE TITLE
How to save a fillable PDF?

### ISSUE THREAD

**Issue by marcoheine** [endigo/flutter_pdfview#233]
I work a lot with editable PDFs. How can these be saved after a user has filled it in?

**Comment by endigo** [comment]
This package has nothing to do with editable PDFs

**Comment by marcoheine** [comment]
@endigo 
I mean something like this:
http://foersom.com/net/HowTo/data/OoPdfFormExample.pdf

It's possible to open such PDFs and fill out the fields. But how can I save this? Is that possible?
