### ISSUE TITLE
app crashes on loading the pdf in release mode

### ISSUE THREAD

**Issue by bishosamer** [endigo/flutter_pdfview#24]
when running in debug mode the plugin works fine but when i release the apk the app crashes once the pdf is loaded

**Comment by endigo** [comment]
Maybe related to #15 

Did you enable proguard?

**Comment by bishosamer** [comment]
yes

**Comment by endigo** [comment]
Please add https://github.com/endigo/flutter_pdfview/issues/15#issuecomment-506307814 these proguard rules then try it again.

**Comment by bishosamer** [comment]
fixed by adding 

-keep class com.shockwave.**
-keepclassmembers class com.shockwave.** { *; }

to the proguard-rules.pro
