### ISSUE TITLE
Possibility to select and copy text to Clipboard.

### ISSUE THREAD

**Issue by GENL** [endigo/flutter_pdfview#25]
Hi! Great library. Can you add the possibility to select and copy a part of the text contained in the PDF file to the clipboard?

**Comment by endigo** [comment]
For android, it is not possible.
https://github.com/barteksc/AndroidPdfViewer/issues/95

**Comment by GENL** [comment]
Okay. Thanks!

**Comment by paaKways** [comment]
Hello, any update on this? I see the AndroidPdfViewer has seen some progress with text selection.
