### ISSUE TITLE
PDFView screen goes blank on Notification drawer extend

### ISSUE THREAD

**Issue by jackhax** [endigo/flutter_pdfview#28]
Whenever i extend the notification drawer the pdf screen goes blank. Any help?

**Comment by endigo** [comment]
Can you explain more? Or please attach a screenshot.

If pdfview size changed, you should re-render the widget.

**Comment by ASemeniuk** [comment]
Actually, PdfView goes blank on any state change.

**Comment by endigo** [comment]
Related to #9
