### ISSUE TITLE
VERSION ISSUE

### ISSUE THREAD

**Issue by irosle** [endigo/flutter_pdfview#3]
Trying to use platform views with API 19, required API level is: 20

**Comment by endigo** [comment]
On the example application, minSdkVersion is 16.
So it won't be a problem.

Can you provide more information? For example minimal repo.

**Comment by endigo** [comment]
Embeds an Android view in the Widget hierarchy.
Requires Android API level 20 or greater.

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/platform_view.dart#L16
