### ISSUE TITLE
Need to customise the UI 

### ISSUE THREAD

**Issue by suyashdixit** [endigo/flutter_pdfview#30]
Hello, 
Great plugin but I need to customize it. For an example of the PDFView, I want to give no elevation with all white background. 
I am a bit new to Flutter so apologies if it is a stupid question.

**Comment by endigo** [comment]
Hello, thanks for using it.

Unfortunately, I think customing UI isn't possible because there are no views or any other widgets. 

The background color is from native libraries, so there is no way to customize it.

**Comment by mvilks** [comment]
@suyashdixit 
The simplest way to do it for iOS is this:

- git clone this repo
- edit `ios/Classes/FlutterPDFView.m` file, replace line 73 with this:
```objective-c
_pdfView.backgroundColor = [UIColor colorWithWhite:1.0 alpha:1.0];
_pdfView.pageShadowsEnabled = NO;
```
- edit your Flutter project's `pubspec.yaml` dependencies:
```yaml
dependencies:
  flutter_pdfview:
    path: ../path_of_your_git_cloned_flutter_pdfview/
```
- do `flutter pub get` and run your project
