### ISSUE TITLE
Download file from url 

### ISSUE THREAD

**Issue by stivoox** [endigo/flutter_pdfview#31]
Hi friends.
I just want to know if there's a way to download file from URL for the first time, then open it from the new path in the next time. 
regards

**Comment by endigo** [comment]
Hello, 

You should store files on a specific path. Then, check the new file is exists on that path, if not download and store it, else open it from that path.

`dio` package can download files.

**Comment by stivoox** [comment]
@endigo : I tried this but doesn't work : 
`try {
      Dio dio = Dio();
      var directory = (await getApplicationDocumentsDirectory()).path;
      final filename = url.substring(url.lastIndexOf("/") + 1);
      if (await File('$directory/$filename').exists()) {
        var data = await rootBundle.load('$directory/$filename');
        var bytes = data.buffer.asUint8List();
        File file = File('$directory/$filename');
        File assetFile = await file.writeAsBytes(bytes);
        return assetFile;
      } else {
        await dio.download(url, '$directory/$filename');
        var request = await HttpClient().getUrl(Uri.parse(url));
        var response = await request.close();
        var bytes = await consolidateHttpClientResponseBytes(response);
        String dir = (await getApplicationDocumentsDirectory()).path;
        File file = new File('$dir/$filename');
        await file.writeAsBytes(bytes);
        return file;
      }
    } catch (e) {
      throw Exception("Error opening url file");
    }`

**Comment by stivoox** [comment]
I tried this but doesn't work : 
`try {
      Dio dio = Dio();
      var directory = (await getApplicationDocumentsDirectory()).path;
      final filename = url.substring(url.lastIndexOf("/") + 1);
      if (await File('$directory/$filename').exists()) {
        var data = await rootBundle.load('$directory/$filename');
        var bytes = data.buffer.asUint8List();
        File file = File('$directory/$filename');
        File assetFile = await file.writeAsBytes(bytes);
        return assetFile;
      } else {
        await dio.download(url, '$directory/$filename');
        var request = await HttpClient().getUrl(Uri.parse(url));
        var response = await request.close();
        var bytes = await consolidateHttpClientResponseBytes(response);
        String dir = (await getApplicationDocumentsDirectory()).path;
        File file = new File('$dir/$filename');
        await file.writeAsBytes(bytes);
        return file;
      }
    } catch (e) {
      throw Exception("Error opening url file");
    }`

**Comment by stivoox** [comment]
I Tried this but doesn't work : 
```
try {
      Dio dio = Dio();
      var directory = (await getApplicationDocumentsDirectory()).path;
      final filename = url.substring(url.lastIndexOf("/") + 1);
      if (await File('$directory/$filename').exists()) {
        var data = await rootBundle.load('$directory/$filename');
        var bytes = data.buffer.asUint8List();
        File file = File('$directory/$filename');
        File assetFile = await file.writeAsBytes(bytes);
        return assetFile;
      } else {
        await dio.download(url, '$directory/$filename');
        var request = await HttpClient().getUrl(Uri.parse(url));
        var response = await request.close();
        var bytes = await consolidateHttpClientResponseBytes(response);
        String dir = (await getApplicationDocumentsDirectory()).path;
        File file = new File('$dir/$filename');
        await file.writeAsBytes(bytes);
        return file;
      }
    } catch (e) {
      throw Exception("Error opening url file");
    }
```

**Comment by stivoox** [comment]
Finally fixed it : 
```
 Future<File> getFileFromUrl(String url) async {
    try {
      Dio dio = Dio();
      var directory = (await getApplicationDocumentsDirectory()).path;
      final filename = url.substring(url.lastIndexOf("/") + 1);
      if (await File('$directory/$filename').exists()) {
        File pdffile = new File('$directory/$filename');
        var data = await pdffile.readAsBytes();
        var bytes = data.buffer.asUint8List();
        var dir = await getApplicationDocumentsDirectory();
        File file = File("${dir.path}/mypdf.pdf");
        File assetFile = await file.writeAsBytes(bytes);
        return assetFile;
      } else {
        await dio.download(url, '$directory/$filename');
        var request = await HttpClient().getUrl(Uri.parse(url));
        var response = await request.close();
        var bytes = await consolidateHttpClientResponseBytes(response);
        String dir = (await getApplicationDocumentsDirectory()).path;
        File file = new File('$dir/$filename');
        await file.writeAsBytes(bytes);
        return file;
      }
    } catch (e) {
      throw Exception("Error opening url file");
    }
  }
```
