### ISSUE TITLE
Add option displayAsBook

### ISSUE THREAD

**Issue by BadTasTe-** [endigo/flutter_pdfview#34]
Hi there, great plugin!
Is there anyway to add this option to the plugin? As far as i know, pdfview from PDFKIT has the property displaysAsBook, but for Android, i don't know.
Do you think you'll be able to add this functionality to the plugin?

Thanks

**Comment by endigo** [comment]
Hello, thanks for trying,

Unfortunately, it's just a side project not a commercial product. Thus, I can't develop native libraries like Pdfkit or Pdftron.

If you are want to develop this feature, your welcome, go on.

Thanks
