### ISSUE TITLE
Landscape mode fullscreen?

### ISSUE THREAD

**Issue by klaszlo8207** [endigo/flutter_pdfview#39]
Any way to show fullscreen that page when we are in landscape mode? (show all as a page)

Now in landscape mode I only see the full page 30%

I don't want to scroll/swype on it

**Comment by a8thunder** [comment]
help me,please

**Comment by arnaudelub** [comment]
i've made an update for that and i've already did the pull request, hope the maintainer is still available

**Comment by endigo** [comment]
Duplicated #9
