### ISSUE TITLE
Wish List: Search 

### ISSUE THREAD

**Issue by l-k22** [endigo/flutter_pdfview#4]
Great package, looks quite flexible. With this I can create my own custom bookmarks feature then use the setpage function to jump to a specific page.

I'd like to implement search and as well as a content page(or return to content page), for greater usability. Do you plan to add anything like this in the near future?

Thanks

**Comment by endigo** [comment]
Hello, thanks for using.

For now, I have no plan to implement search functionality.
If you can help with this functionality PRs are welcome.

Thanks.

**Comment by endigo** [comment]
Search is not possible to implement because native libraries are only supporting view-only, which means there is no text-layer to find any text. Therefore, I close this issue.
