### ISSUE TITLE
App crashes when loading the pdf in release build

### ISSUE THREAD

**Issue by rakib205** [endigo/flutter_pdfview#41]
In debug version, everything is ok. Any solution?

**Comment by rakib205** [comment]
@endigo please check.

**Comment by tlueder** [comment]
@rakib205 pleas have a look at this.
https://github.com/endigo/flutter_pdfview/issues/24#issuecomment-529968418

**Comment by endigo** [comment]
@rakib205 https://github.com/endigo/flutter_pdfview#for-production-usage

**Comment by rakib205** [comment]
@tlueder @endigo  thanks.

**Comment by rakib205** [comment]
@endigo I noticed that without proguard it crashes. So, Everyone have to use proguard to use this package for production.
