### ISSUE TITLE
"CocoaPods could not find compatible versions for pod" issue is occurring during ios app build for release

### ISSUE THREAD

**Issue by DevXtranet** [endigo/flutter_pdfview#42]
CocoaPods could not find compatible versions for pod "flutter_pdfview":
      In Podfile:
        flutter_pdfview (from `.symlinks/plugins/flutter_pdfview/ios`)

    Specs satisfying the `flutter_pdfview (from `.symlinks/plugins/flutter_pdfview/ios`)` dependency were found, but they required a higher minimum deployment target.

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

So please let me know the minimum ios version this package support?.
Thanks in advance.

**Comment by tlueder** [comment]
Your minimum deployment target must be >= 11.0

**Comment by endigo** [comment]
Required deployment target version must be => 11.0 because PDFView was introduced in v11.0.
