### ISSUE TITLE
Please verify that file has read permission and try again.

### ISSUE THREAD

**Issue by PritishSawant** [endigo/flutter_pdfview#48]
I have integrated your library in my app. Whenever i do pub get i get following C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_pdfview-1.0.0+11\android\src\main\kotlin\io\endigo\plugins\pdfviewflutter\PDFFlutterPlugin.kt' even though it exists. Please verify that this file has read permission and try again.

**Comment by endigo** [comment]
Sorry to bother you, I fixed it. Please use 1.0.0+12

**Comment by PritishSawant** [comment]
@endigo Thanks for the fix. I have not updated to 1.0.0+12, but I fixed it by adding pro guard file to android app and wrote the shockwave line in it
