### ISSUE TITLE
App crashing when in production

### ISSUE THREAD

**Issue by arnaudelub** [endigo/flutter_pdfview#49]
Hi,

since your last update, app is crashing when opening the PDF.

Steps to reproduce:
- clone the package
- go to exemple folder
-run "flutter build apk"
- install the APK on the device
-run the app and open the pdf, the app should crash

**Comment by endigo** [comment]
@arnaudelub Hello, 
I didn't enable proguard for example. If you want to test,  you have to read this.

https://github.com/endigo/flutter_pdfview#for-production-usage
