### ISSUE TITLE
Upgrade from 1.0.0+10 to 1.0.1 breaks app on android

### ISSUE THREAD

**Issue by function1983** [endigo/flutter_pdfview#50]
Today I hit the upgrade button and 1.0.1 broke flutter on Android (both emulator and real device) with following error on the emulator:

```
D/com.shockwave.pdfium.PdfiumCore(28811): Starting PdfiumAndroid 1.9.0
D/EGL_emulation(28811): eglMakeCurrent: 0xebc1cc40: ver 2 0 (tinfo 0xd586e540)
I/flutter (28811): [onError, {error: java.io.FileNotFoundException: No content provider: /data/user/0/****/app_flutter/****.pdf}]
I/flutter (28811): java.io.FileNotFoundException: No content provider: /data/user/0/****/app_flutter/****.pdf
```

I confirmed the behavior by downgrading to 1.0.0+10 (works) and then upgrading back to 1.0.1 (broken). The error persists using both path_provider getTemporaryDirectory() and getApplicationDocumentsDirectory() functions.

My flutter doctor output for your reference:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.6)
[!] VS Code (version 1.42.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)
```

**Comment by endigo** [comment]
I think it is not related to the package.
Here is the guide, how to solve those kinda problems,
https://stackoverflow.com/questions/3288619/what-to-do-when-java-io-filenotfoundexception-no-content-provider
