### ISSUE TITLE
after build apk, cannot view pdf in app

### ISSUE THREAD

**Issue by Silerqin** [endigo/flutter_pdfview#51]
Hi, I have an issue when I build the apk then I open pdf in app. The app will close but in the debug mode is working. Can you help me? Thanks in advanced

**Comment by Tapaswi846580** [comment]
Hi @Silerqin, I have got the same issue and I got it solved by adding proguard for android and add the following line in the proguard
_-keep class com.shockwave.**_

Refer to the following link for more
https://pub.dev/packages/flutter_pdfview#for-production-usage

Hope this will solve your issue.

**Comment by Silerqin** [comment]
@Tapaswi846580 Thank you for your help. After I add proguard file it works. Thank you very much

**Comment by Tapaswi846580** [comment]
> @Tapaswi846580 Thank you for your help. After I add proguard file it works. Thank you very much

Your Most Welcome !! 😉😉
