### ISSUE TITLE
PDF show blank page when running on Android native

### ISSUE THREAD

**Issue by dochanhca** [endigo/flutter_pdfview#53]
It's work fine on Android when i running flutter app but when i import flutter as a module on android native app. I'm getting this error on logcat:
`
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method create on channel flutter/platform_views)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
    <asynchronous suspension>
    #1      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
    #2      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
    #3      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
    #4      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
    #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
    #6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #8      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
    #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #10     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:806:17)
    #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #14     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
    #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #22     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:392:13)
    #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #29     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3168:13)
    #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #31     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
    #32     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
    #33     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
    #34     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
    #35     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
    #36     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
    #37     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
    #38     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
    #39     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
    #40     _rootRun (dart:async/zone.dart:1126:13)
    #41     _CustomZone.run (dart:async/zone.dart:1023:19)
    #42     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #43     _invoke (dart:ui/hooks.dart:259:10)
    #44     _drawFrame (dart:ui/hooks.dart:217:3)
`

**Comment by breunibes** [comment]
I can confirm this. This warning is displayed during build:

```
The plugin `flutter_pdfview` is built using an older version of the Android plugin API which assumes that it's
running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an
existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following
https://flutter.dev/go/android-plugin-migration.
```
