### ISSUE TITLE
Closing on Device

### ISSUE THREAD

**Issue by wesleytoshio** [endigo/flutter_pdfview#54]
in the production version the application runs normally, but when I create the release version the application closes on its own, I am using the real version 1.0.0 + 10

``` dart
PDFView(
   filePath: urlPDFPath,
   autoSpacing: true,
   enableSwipe: true,
   pageSnap: true,
   swipeHorizontal: true,
   nightMode: false
)
```

**Comment by ishukumar5663** [comment]
Same problem bro!!

**Comment by endigo** [comment]
You need to enable proguard in some cases. 
https://github.com/endigo/flutter_pdfview#for-production-usage

**Comment by wesleytoshio** [comment]
> You need to enable proguard in some cases.
> https://github.com/endigo/flutter_pdfview#for-production-usage

where do i put this?

**Comment by endigo** [comment]
@wesleytoshio 
Here is guide
https://stackoverflow.com/questions/52428973/how-to-minify-a-flutter-app-with-proguard

but there is a new way to shrink the app 
https://flutter.dev/docs/deployment/android#r8
and it's enabled by default. I'm afraid maybe this plugin is not compatible with this.
