### ISSUE TITLE
error: java.io.FileNotFoundException: No such file or directory

### ISSUE THREAD

**Issue by samycodes** [endigo/flutter_pdfview#55]
When I run `flutter run` sometimes I get this error:

```
I/flutter (12110): [onError, {error: java.io.FileNotFoundException: No such file or directory}]
I/flutter (12110): java.io.FileNotFoundException: No such file or directory                                        
I/flutter (12110): /data/user/0/com.example.myapp/app_flutter/mypdf.pdf  
```

Can somebody help me to resolve this issue?

**Comment by endigo** [comment]
Hello, I tested my example app. But I can't reproduce this issue.

Maybe you should check again the file path.

Here is an example of download and store file in the application directory

https://github.com/endigo/flutter_pdfview/blob/master/example/lib/main.dart#L43
