### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by emreesen27** [endigo/flutter_pdfview#56]
The pdf viewer shows a white screen when used for a long time and throws the warning 
" The application may be doing too much work on its main thread."

**Comment by endigo** [comment]
In android?
You need to search from https://github.com/barteksc/AndroidPdfViewer/issues

**Comment by emreesen27** [comment]
Thanks for your answer.
I use flutter but the problem is only experienced on android.

**Comment by YemaneZewdu** [comment]
Hi @endigo,
I have a similar issue. It shows a white screen when I fast swipe multiple pages at a time. The page transitions aren't as smooth as a normal PDF scrolling. Do you have any suggestions?

Thanks!
