### ISSUE TITLE
Pdfview cannot load pdf even after permission for Read and write in storage is granted

### ISSUE THREAD

**Issue by Bidhanrai** [endigo/flutter_pdfview#61]
error: java.io.FileNotFoundException: Permission denied

path to pdf: /data/user/0/com.example.lmsandroid/app_flutter/myPdf.pdf

**Comment by endigo** [comment]
Hello, please show your codes.

**Comment by Bidhanrai** [comment]
it was my some silly  fault. Plugin worked perfectly fine. Thank you very
much for building this plugin. :-)

**Comment by adnan-atif** [comment]
@Bidhanrai  could you please tell what was the mistake i am also stuck in same issue.

**Comment by adnan-atif** [comment]
@endigo ?
