### ISSUE TITLE
Deploying with CodeMagic

### ISSUE THREAD

**Issue by M1Joe** [endigo/flutter_pdfview#62]
Sorry to ask a question in here, but figured it'd be a helpful place in case others have the same question... I'm trying to use codemagic.io to build and release an application without purchasing a magic.  Can anyone tell me how to increase the minimum deployment target for iOS to the required 11?  

I can't see it anywhere in the iOS folder.  THANK YOU!

**Comment by endigo** [comment]
You set it in here
<img width="1026" alt="Screen Shot 2020-04-30 at 10 06 54 AM" src="https://user-images.githubusercontent.com/1501644/80664849-70e05b80-8aca-11ea-8dcb-81e3f309fb8a.png">

**Comment by M1Joe** [comment]
@endigo I should have specified that I'm trying to do this without a Mac...

**Comment by endigo** [comment]
File path `ios/Runner.xcodeproj/project.pbxproj`

find and edit line `IPHONEOS_DEPLOYMENT_TARGET = 11.0;`
