### ISSUE TITLE
scrollbar in wrong position

### ISSUE THREAD

**Issue by The-Redhat** [endigo/flutter_pdfview#67]
![WhatsApp_Image_2020-02-19_at_20 14 26](https://user-images.githubusercontent.com/33162310/83009639-55a83380-a017-11ea-8f43-7b5944daea24.jpeg)

Maybe this issue from flutter_webview is able to help:  https://github.com/flutter/flutter/issues/41592 or https://github.com/flutter/plugins/pull/2343

**Comment by endigo** [comment]
Fixed in 1.0.2+1.

But there is an issue when you set one of these `autoSpacing, pageFling` fields to `true`

**Comment by The-Redhat** [comment]
Thanks man
