### ISSUE TITLE
PDF file not opening

### ISSUE THREAD

**Issue by TAMU73** [endigo/flutter_pdfview#69]
PDF file is only opening in emulator of Android Studio. And then when I release it and install on my phone, its not opening. Whats the problem?

Edit: It worked after I obfuscate the flutter app and added the line told by this package to proguard. 
Thank You.

**Comment by endigo** [comment]
Please provide more informations,

like logcat, logs etc

**Comment by TAMU73** [comment]
![image](https://user-images.githubusercontent.com/47109205/83259144-3fe16c80-a1d7-11ea-917f-91ebe8fb18f2.png)

**Comment by TAMU73** [comment]
![image](https://user-images.githubusercontent.com/47109205/83259252-6f907480-a1d7-11ea-909b-c123b1df58f4.png)

**Comment by TAMU73** [comment]
![image](https://user-images.githubusercontent.com/47109205/83259335-964eab00-a1d7-11ea-84df-11c94c93d390.png)

**Comment by TAMU73** [comment]
![image](https://user-images.githubusercontent.com/47109205/83259440-c4cc8600-a1d7-11ea-8eb6-2bf02162b3f1.png)

**Comment by TAMU73** [comment]
![image](https://user-images.githubusercontent.com/47109205/83326541-8d6fdf00-a294-11ea-9e42-a9ec90806553.png)
But when i connect to my phone and run it in debug mode it opens and the pdf file shows this message which I am not understanding. Hope you will find the solution.

**Comment by endigo** [comment]
@TAMU73 Please share your solutions

**Comment by TAMU73** [comment]
@endigo I have mentioned the solution in my question at edit section. I think it makes easier to find the exact solution without scrolling.
Thank You.
