### ISSUE TITLE
strange message

### ISSUE THREAD

**Issue by egodefroy** [endigo/flutter_pdfview#7]
Not sure it's related but I got this message with certain pdf files:
````
Hit tagged parsing error, fatal: "Missing "Properties" dictionary from page resources dictionary"
````
Otherwise, I cannot get the 'onRender' event with 1.0.0+5 release on iOS, so, following your example, the state of the CircularProgressIndicator cannot be changed

**Comment by endigo** [comment]
Related #6

**Comment by endigo** [comment]
I working on this
