### ISSUE TITLE
How to change the night mode during runtime  ?

### ISSUE THREAD

**Issue by lordjoo** [endigo/flutter_pdfview#74]
Hi my friend your plug-in is so great 
But I'm trying to make a button to trigger the night mode in my app but i cannot do this 
I'm using statefull widget and setState to change the value of the variable responsible for the night mode but i found that the pdf is still using the initial value i gave

**Comment by razein97** [comment]
The Logical Steps you could take are:
1. Get the current page of the pdf file.
2. Then load the pdf file again with option night mode = true, the initial page as the current page that you got.

**Comment by raunak-many-ac** [comment]
Just do a setState() dude...its as simple as that...
