### ISSUE TITLE
Hyperlinks

### ISSUE THREAD

**Issue by Johannes11833** [endigo/flutter_pdfview#75]
Is it possible to listen to clicks on links and handle such events?

**Comment by stefalda** [comment]
I've added that support because I needed too, and provided a pull request.
If you want to experiment it you can check my [fork](https://github.com/stefalda/flutter_pdfview)...

**Comment by endigo** [comment]
#81

**Comment by Johannes11833** [comment]
> I've added that support because I needed too, and provided a pull request.
> If you want to experiment it you can check my [fork](https://github.com/stefalda/flutter_pdfview)...

Thanks a lot! This works quite well.
