### ISSUE TITLE
Ability to Search PDF Text

### ISSUE THREAD

**Issue by anandatman** [endigo/flutter_pdfview#83]
After spending considerable time here, in pub.dev, and in the Flutter and Dart docs, I've discovered very little on the topic of Searchable PDFs.  On the IOS side, It looks like PDFKit supports search in the PDFDocument class, but I'm not sure about the Android implementation.  Any idea on what it would take to include that functionality in flutter_preview?

I'm fairly new to Flutter, so if I'm missing something obvious, please excuse my ignorance.  Thanks in advance for any advice and helping point me in the right direction

**Comment by endigo** [comment]
Right now, in this plugin, it's impossible to search from pdf.

**Comment by kateile** [comment]
Hi @anandatman , have you found solution for this?
