### ISSUE TITLE
Links inside pdf crashes the app when tapped

### ISSUE THREAD

**Issue by akatski316** [endigo/flutter_pdfview#85]
I just put a link inside a pdf it works fine on desktop, but in my app these links just crashes the application with following errors:-

![Screenshot_2020-07-07-09-31-07-419_com google android apps playconsole](https://user-images.githubusercontent.com/31949358/86706582-aa869300-c034-11ea-8389-3f01e1557317.jpg)

![Screenshot_2020-07-07-09-31-58-015_com google android apps playconsole](https://user-images.githubusercontent.com/31949358/86706675-c427da80-c034-11ea-8fd6-aa62c6a2ea02.jpg)

Sir its my humble request., please help because links are crucial part of documents...

**Comment by akatski316** [comment]
I tried a lot, but don't know how to launch an intent from inside of a pdf in the app to a browser....

**Comment by sekharjha** [comment]
@endigo I also faced the same issue but never found a way to solve it ..would be helpful if this is fixed.

**Comment by endigo** [comment]
@stefalda Did face the same issue? Can you give them some explanation?

**Comment by stefalda** [comment]
Are you using complete URLsuch as https://www.google.com?
Can you provide me an example?

**Comment by stefalda** [comment]
It depends on what you're trying to achieve.
If you want to open a link you have two options:
1.  implement  the _onLinkHandler_ just to be notified of the clicked link
2. setting the `preventLinkNavigation=true` and implement your link logic inside the _onLinkHandler_ method

In the second case you could handle custom urls embedded in the pdf or using something like the _url_launcher_ package to open the link.

**Comment by akatski316** [comment]
@stefalda My very sincere thanka to you first.... here is an example link..... https://atcoder.jp/contests/dp/tasks/dp_a

It seems like i got what you said, i will try doing the same as you said in the last comment and will get back to you if i get stuck....

Thanks again...

**Comment by stefalda** [comment]
@akatski316 I've made some tests with latest version and everything seems to work as described in the comment below... 
let me know if it works...
