### ISSUE TITLE
Crashing in release build

### ISSUE THREAD

**Issue by nishanthrk** [endigo/flutter_pdfview#86]
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.2 19C57, locale en-IN)
    • Flutter version 1.17.5 at /usr/local/flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nishanth/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2020.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • POCO F1 • 2a1d55d8 • android-arm64 • Android 10 (API 29)

**Comment by nishanthrk** [comment]
When we are using --no-shrink then it's not crashing

**Comment by tlueder** [comment]
Please read the docs

https://github.com/endigo/flutter_pdfview#for-production-usage

**Comment by renenucci** [comment]
> Please read the docs
> 
> https://github.com/endigo/flutter_pdfview#for-production-usage

Hi, I saw this but, I dont setup proguard, (not me at least, and idk if flutter enables this feature as default, I haven't found any proguard settings in my project), so, idk where to put `-keep class com.shockwave.**` or how it should work, can you explain to me?

ty!

**Comment by endigo** [comment]
@renenucci Hello, thanks for using it.
First, you need to learn about shrinking here.
https://developer.android.com/studio/build/shrink-code

Now android uses R8 instead of ProGuard but it still use same configuration.

**Comment by endigo** [comment]
https://medium.com/@imstudio/android-journey-proguard-d8-r8-what-are-they-e8f2bfe079a7
