### ISSUE TITLE
FileNotFoundException: EACCES (Permission denied)

### ISSUE THREAD

**Issue by yskhs07** [endigo/flutter_pdfview#98]
Getting this error on android 
on Android.
FileNotFoundException: EACCES (Permission denied)
Getting this error so many times while viewing pdf. Some pdf are loading very rarely

my-code ::
Basically almost the same code
![as](https://user-images.githubusercontent.com/38002268/90639827-dd838f80-e24c-11ea-89b4-f5ba230ff8c3.PNG)
![2](https://user-images.githubusercontent.com/38002268/90639829-df4d5300-e24c-11ea-8184-878559b34fdf.PNG)

**Comment by endigo** [comment]
Can you show me how widget.path variable gets value?

**Comment by yskhs07** [comment]
I added print in build function this is the screenshot.. I can see it's getting the path very late .. why is it happening and how can I fix this. Thanks!!
![4](https://user-images.githubusercontent.com/38002268/90646080-67832680-e254-11ea-8bb8-a011e586e1b4.PNG)

**Comment by endigo** [comment]
Maybe you should remove that query params from pdf name. I think it's not a valid filename

**Comment by yskhs07** [comment]
I think it's a valid filename, it working for now I guess as I awaited to pass that filePath by
![asddada](https://user-images.githubusercontent.com/38002268/90652463-b97b7a80-e25b-11ea-9d55-896124eda40e.PNG)

**Comment by yskhs07** [comment]
Btw I appreciate your fast response and help. Thanks brother !!
